name: Build and Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ./sample-vite/package-lock.json
      - name: Install dependencies
        run: npm ci #より確実な依存関係のインストールを行う
        working-directory: ./sample-vite  # 実行ディレクトリを設定
      - name: Run build
        run: npm run build
        working-directory: ./sample-vite  # 実行ディレクトリを設定
      - name: Install firebase-tools
        run: npm install --save-dev firebase-tools
        working-directory: ./sample-vite  # 実行ディレクトリを設定
      - name: Decode Firebase service account key
        run: |
          echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-key.json" >> $GITHUB_ENV
      - name: change space
        run: ./node_modules/.bin/firebase use ${{ secrets.FIREBASE_PROJECT_ID }}
        working-directory: ./sample-vite  # 実行ディレクトリを設定
      - name: Deploy to Firebase Hosting
        run: |
          ./node_modules/.bin/firebase deploy --only hosting
        working-directory: ./sample-vite  # 実行ディレクトリを設定
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: delete GOOGLE_APPLICATION_CREDENTIALS
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
